api/urls.py
from django.conf.urls import url, include, patterns
from api import views

urlpatterns = patterns('',
    #url(r'^employees/$', views.EmployeeList.as_view(), name = "employee_list"),
    url(r'^employees/$', views.EmployeeList.as_view()),
    url(r'^employees/(?P<pk>\d+)/$', views.EmployeeDetail.as_view()),
    url(r'^employees/(?P<pk>\d+)/works/$', views.EmployeeWorkList.as_view()),
    url(r'^works/$', views.MonthlyWorkList.as_view()),
    url(r'^works/week/(?P<year>\d+)/(?P<week_num>\d+)/$', views.WeeklyWorkList.as_view()),
    url(r'^api_demo/$', views.DemoCreate.as_view()),
    )

registration/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns('',
                   #url(r'^register/$', views.register, name='register'),
                   url(r'^login/$','django.contrib.auth.views.login', name='login'),
                   url(r'^logout/$','django.contrib.auth.views.logout',{'next_page':'/accounts/login/'}, name='logout'),
                     )

schedule/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    # Examples:
    url(r'^$', 'timetable.views.home', name='home'),
    url(r'^accounts/', include('registration.urls', namespace='registration')),
    url(r'^schedule/', include('timetable.urls', namespace='employee_schedule')),
    url(r'^messageboard/', include('messageboard.urls', namespace='messageboard')),
    url(r'^employer/', include('employer.urls', namespace="employer")),
    url(r'^api/',include('api.urls', namespace = "api")),
    url(r'^api-auth/', include('rest_framework.urls', namespace = "rest_framework")),
    url(r'mydemo/$','timetable.views.demo'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
)

timetable/urls.py
from django.conf.urls import patterns, include, url
from timetable import views

urlpatterns= patterns('',
        #url(r'^userpage/$', views.userpage, name="userpage"),
        url(r'^dashboard/$', views.dashboard, name="dashboard"),
        url(r'^cal/(?P<cal_year>\d+)/(?P<cal_month>\d+)/$', views.calendar, name="calendar"),
        url(r'^cal/(?P<cal_year>\d+)/(?P<cal_month>\d+)/(?P<cal_day>\d+)/$', views.day_view, name="day_view"),
        url(r'^ajax_day_view/$', views.ajax_day_view, name="ajax_day_view"),
        url(r'^myrequest/$', views.myrequest, name="myrequest"),
        
    )

templates/base.html
{% load staticfiles %}
{% load current_date %}
{% get_current_date as the_date %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    
        <title>smartsched</title>

    <!-- Bootstrap -->
        <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
       <link rel="stylesheet" href="{% static 'css/simple-sidebar.css' %}">
       {% block stylesheets %}{% endblock %}
    </head>
    
  <body>
      <nav class="navbar navbar-inverse navbar-fixed-top">
          
        <div class="container">
            <div class="navbar-header pull-left">
                
                <button type="button" class="navbar-toggle pull-left visible-xs" id="menu-toggle">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                
                <a class="pull-left navbar-brand" href="#">SCHED</a>
            </div>
          
            <div class="navbar-header pull-right">
                <ul class="nav pull-left">
                    <li class="pull-left"><a href="#" style="margin-top:5px;"><span class="glyphicon glyphicon-globe"></span>
                    <span class = "badge badge-notify">3</span>
                    </a>
                    
                    </li>
                    
                    <li class="dropdown pull-right">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#" style= "margin-top: 5px;"><span class="glyphicon glyphicon-cog"></span><b class="caret"></b>
                        </a>
                        <ul class="dropdown-menu">
                            <li><a href="#">Privacy</a></li>
                            <li><a href="#">Change password</a></li>
                            <li><a href="#">Logout</a></li>
                        </ul>
                    </li>
                
                    <li class="pull-left"><a href="#" style= "margin-top: 5px;"><span class="glyphicon glyphicon-user"></span></a></li>
                    
                </ul>
            </div>
        </div>
</nav>


    


   
<div id="wrapper">
    
        <!-- Sidebar -->
        <div id="sidebar-wrapper">
            <ul class="sidebar-nav">
                <li>
                     <a href="/messageboard/messages"><i class="fa fa-tachometer fa-lg"></i><span> Message Board</span></a>
                </li>
                <li>
                    <a href="{% url 'employee_schedule:calendar' the_date.year the_date.month %}"><i class="fa fa-calendar fa-lg"></i> View Calendar</a>
                </li>
                <li>
                    <a href="#"><i class="fa fa-share fa-lg"></i> Make Request</a>
                </li>
                <li>
                    <a href="#"><i class="fa fa-exchange fa-lg"></i> Swap workday</a>
                </li>
                <li>
                    <a href="#"><i class="fa fa-random fa-lg"></i> Replace Work</a>
                </li>
                <li>

            </ul>
        </div>
        <!-- /#sidebar-wrapper -->

        <!-- Page Content -->
        <div id="page-content-wrapper">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-12">
                        
                        {% block heading %}
                        
                        {% endblock %}
                    </div>
                </div>
                        {% block content %}
                            
                               
                        {% endblock %}
                
            </div>
        </div>
        <!-- /#page-content-wrapper -->

    </div>


    <!-- /#wrapper -->

   <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
      {% block scripts %}
      
      {% endblock %}
          
      
      <script>
      
    $("#menu-toggle").click(function(e) {
        
        e.preventDefault();
        $("#wrapper").toggleClass("toggled");
    });
    
   
    </script>
    
    
      
  </body>

    
</html>

templates/demo.html
{% extends "base.html" %}
{% load staticfiles %}
<!DOCTYPE html>

{% block content %}
        <div ng-app = "myApp">
        {% verbatim %}
        <div class = "row">
            
            <div class="col-md-8">
                <div class="panel panel-primary">
                    <div class="panel-heading">Django REST with Angular</div>
                    
                <!--<div class="pane-body" ng-controller="mainController">
                    <input type="text" class="form-control" ng-model="newPost" placeholder="Please enter something to post" required/>
                    
                    <input type="button" class="btn btn-success btn-block" ng-click="addMe()" value="Post"/>
                    <ul class="list-group">
                        <li class="list-group-item" ng-repeat=" mypost in posts ">
                            {{ mypost.post }}
                        </li>
                    </ul>
                </div>
            </div>
            </div> -->
            <demo-directive></demo-directive>
           
            
            <div ng-view></div>
            
                 <div class = "col-md-4">
                     
            </div>
        
       
        {% endverbatim %}
        </div>
{% endblock %}

{% block scripts %}
            <script src="https://code.angularjs.org/1.4.7/angular.min.js"></script>
            
            <script src="https://code.angularjs.org/1.4.7/angular-route.min.js"></script>
            <script src = "{% static 'angular/app.js' %}"></script>

{% endblock %}

templates/employer_base.html
{% load staticfiles %}
{% load current_date %}
{% get_current_date as the_date %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    
        <title>smartsched</title>

    <!-- Bootstrap -->
        <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
       <link rel="stylesheet" href="{% static 'css/simple-sidebar.css' %}">
       {% block stylesheets %}{% endblock %}
    </head>
    
  <body>
      <nav class="navbar navbar-inverse navbar-fixed-top">
          
        <div class="container">
            <div class="navbar-header pull-left">
                
                <button type="button" class="navbar-toggle pull-left visible-xs" id="menu-toggle">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                
                <a class="pull-left navbar-brand" href="#">SCHED</a>
            </div>
          
            <div class="navbar-header pull-right">
                <ul class="nav pull-left">
                    <li class="pull-left"><a href="#" style="margin-top:5px;"><span class="glyphicon glyphicon-globe"></span>
                    <span class = "badge badge-notify">3</span>
                    </a>
                    
                    </li>
                    
                    <li class="dropdown pull-right">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#" style= "margin-top: 5px;"><span class="glyphicon glyphicon-cog"></span><b class="caret"></b>
                        </a>
                        <ul class="dropdown-menu">
                            <li><a href="#">Privacy</a></li>
                            <li><a href="#">Change password</a></li>
                            <li><a href="#">Logout</a></li>
                        </ul>
                    </li>
                
                    <li class="pull-left"><a href="#" style= "margin-top: 5px;"><span class="glyphicon glyphicon-user"></span></a></li>
                    
                </ul>
            </div>
        </div>
</nav>


    


   
<div id="wrapper">
    
        <!-- Sidebar -->
        <div id="sidebar-wrapper">
            <ul class="sidebar-nav">
                <li>
                     <a href="/messageboard/messages"><i class="fa fa-tachometer fa-lg"></i><span> Message Board</span></a>
                </li>
                <li>
                    <a href="{% url 'employee_schedule:calendar' the_date.year the_date.month %}"><i class="fa fa-calendar fa-lg"></i></a>
                </li>
                <li>
                    <a href="#"><i class="fa fa-share fa-lg"></i> Make Request</a>
                </li>
                <li>
                    <a href="#"><i class="fa fa-exchange fa-lg"></i> Swap workday</a>
                </li>
                <li>
                    <a href="#"><i class="fa fa-random fa-lg"></i> Replace Work</a>
                </li>
                <li>

            </ul>
        </div>
        <!-- /#sidebar-wrapper -->

        <!-- Page Content -->
        <div id="page-content-wrapper">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-12">
                        
                        {% block heading %}
                        
                        {% endblock %}
                    </div>
                </div>
                        {% block content %}
                            
                               
                        {% endblock %}
                
            </div>
        </div>
        <!-- /#page-content-wrapper -->

    </div>


    <!-- /#wrapper -->

   <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
      {% block scripts %}
      
      {% endblock %}
          
      
      <script>
      
    $("#menu-toggle").click(function(e) {
        
        e.preventDefault();
        $("#wrapper").toggleClass("toggled");
    });
    
   
    </script>
    
    
      
  </body>

    
</html>

templates/front_base.html
{% load staticfiles %}
<!DOCTYPE html>

<html lang="en" xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{% static "css/frontpage.css" %}">
    
    <title>My bootstrap Page</title>
</head>
<body>

    <nav class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#mynavbar">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">SMARTSCHED</a>
            
                
             </div>
                         
            <div class="collapse navbar-collapse" id="mynavbar">
                <ul class="nav navbar-nav">
                    <li class="active"><a href="{%url 'home' %}">Home</a></li>
                    <li><a href="about.html">Features</a></li>
                    <li><a href="contact.html">pricing</a></li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="{% url 'registration:login' %}"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
                </ul>
            </div>
       </div>
    </nav>
    
    <section>
        {% block content %}
        {% endblock %}
    </section>
    
    <footer>
        <div class="container-fluid">
            <div class="row" id="foot">
                <div class="col-xs-6 " style="background-color: black; color:white;">
                    
                    <p>Copyright @Anish Nepal</p>
                </div>
                <div class="col-xs-6" style="background-color: grey; color:white;">
                    <p>Be connected with us</p>
                    <span><i class="icon-large icon-facebook icon-white"></i></span>
                        
                    
                </div>
            </div>
        </div>
    </footer>
    
</body>
    
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>

</html>

templates/frontpage.html
{% extends 'front_base.html' %}
{% load staticfiles %}
    {% block content %}
          <div class="jumbotron text-center">
              <div class="container-fluid">
                    <div class="row">
                        <div class="col-xs-12 col-md-12 col-sm-12">
                            <h1> A smart scheduling solution</h1>
                            <p class="text-info">
                                .....probably the most easy way to view and manage your schedule.<br> Login now to start viewing your                                   schedule.
                            </p>
                            
                            <a class="btn btn-primary btn-lg" href="{% url 'registration:login' %}" role="button">Login</a>
                            
                        </div>
              
                    </div>
                </div>
          
            </div>

    <section>
        <div class="container">
            <div class="row">
                <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6" >
                    <h1>Easy Scheduling</h1>
                    <hr>
                   <ul id= "feature-list">
                        <li>Easily upload your schedule from Excel to the web</li>
                        <li>Individual calendar for each employee</li>
                        <li>Visual representation of workday, freeday</li>
                        <li>Asking freeday or workday made easy</li>
                        <li>Fabulous approval system for supervisor</li>
                    </ul>
                </div>
                <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
                    <img src="{% static "img/frontpageimage.jpg" %}" class="img-responsive" alt="#" />
                </div>
            </div>
            <div class="row text-center">
                <h1 class="text-cener">Our partner companies..</h1>
                <hr>
                <h2 class="text-center">Companies happily using our solution.</h2>
            </div>
            
            <div class="row">
                <h1>Are you Employer?</h1>
                <hr>
                <p class="lead"> If you are an employer and want to use our application for easy schedule
                management please follow the below link.<br>
                    **Note: fees may apply.</p>
                <center><a href="#" class="btn btn-lg btn-primary">I am employer!!</a></center>
            </div>
            <hr>
        </div>
    </section>
    {% endblock %}
    
    